version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: monthly
        allow:
            - dependency-type: development
        versioning-strategy: increase
        groups:
            dev-dependencies:
                dependency-type: development
                update-types:
                    - minor
                    - patch
